version: '3'
services:

  web:
    image: nginx
    volumes:
    - ./nginx/site.dev.conf:/etc/nginx/conf.d/site.conf
    - ./nginx/logs:/var/log/nginx
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    restart: always
    networks:
      - web-network

  dev:
    image: node:11
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm start
    ports:
      - 1234:1234
      - 1235:1235
    networks:
      - web-network

networks:
  web-network: